### ISSUE TITLE
drop_privileges checks if it's run as root by using getuid

### ISSUE THREAD

**Issue by n-epifanov** [myfreeweb/pysectools#1]
Hi,

man geteuid says:
"When a set ID program is executed the real user ID is set to  the  calling  user  and  the
       effective user ID corresponds to the set ID bit on the file being executed."
Shouldn't be drop_privileges checking with geteuid then?
https://github.com/myfreeweb/pysectools/blob/master/pysectools/__init__.py#L91

**Comment by valpackett** [comment]
Thanks!
