### ISSUE TITLE
PRs welcome?

### ISSUE THREAD

**Issue by apiology** [myfreeweb/pysectools#2]
Hi!

I'm interested in using this project!  A few thoughts on changes I'd love to make, though:

*  Python 3 support
* A couple of stream-related `.flush()` additions to make things work for me (possibly related to Python 3 support?)
* Adding handling of the ERR response (e.g., when someone hits the cancel button on a GUI pinentry)

Would you be willing to look at some PRs I create?  Any strong preferences on how I go about them?

**Comment by valpackett** [comment]
Hi! As you can see, it's pretty abandoned. I'm not using Python a lot these days.

~~Though I see this includes RNG stuff. I'll try to add the modern `getrandom`/`getentropy` functions here…~~ Modern Python uses getentropy when reasonable, and we try `os.urandom` first here.

Of course PRs are okay, but I'd rather add you as collaborator on here and on PyPI and let you do whatever you want :)

**Comment by apiology** [comment]
Works for me!  I'm `apiology` on PyPI as well.

**Comment by apiology** [comment]
Thanks!  Will push up the rest of my changes and publish a release.  Feel free to hit me up if you see any things you do want to talk through, for sure - happy to discuss and/or revert if you see anything troublesome.
