### ISSUE TITLE
affirming the pinentry prompt without a password never echos "D ", and hangs

### ISSUE THREAD

**Issue by ghost** [myfreeweb/pysectools#3]
If the user selects OK without providing a password, I get "OK" back from the pinentry program,
this happens on all of the following, So i think this is a mishandled case
penentry-tty
penentry-curses
penentry-gnome3

Since, self._waitfor is blocked on pinentry for more to read, therefore a password result is never set, therefore a password validator does not mitigate this bug

Looking at the source, I don't see a "one line fix" for this behaviour; 
I tried putting a cap on the number of lines _waitfor would read before giving up; but because of the blocking hang, that doesn't help.

maybe permitting what to be a list and checking for ["D ", "OK"] would be the simplest change?

**Comment by apiology** [comment]
@ava-dylang: Yep, I definitely see bad behavior in this case.  Your approach sounds plausible - feel free to open up a PR if you'd like to give it a shot?

**Comment by apiology** [comment]
(I tested with pinentry-mac, for what it's worth)
